### ISSUE TITLE
本地如何调试呢？

### ISSUE THREAD

**Issue by dgzGitHub** [StandOutstar/Pytest_Allure_Airtest_Demo#4]

**Comment by dgzGitHub** [comment]
win+pychram怎么调试

**Comment by StandOutstar** [comment]
在“注意”章节里 我写过 “本地运行单个用例建议使用 pycharm，添加 pytest 并设置参数运行 ”，如果您对在 pycharm 中添加 py 文件或 Python test 运行器熟悉的话便可以知道如何配置了，可以看下示例图片。如问题已解决，请关闭。
